// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtaXtMoANAON7OlhZnMHhFzW80QN_a9JI',
    appId: '1:622273845776:web:df1dde1f47e5d703404895',
    messagingSenderId: '622273845776',
    projectId: 'fcmtest-ac9ee',
    authDomain: 'fcmtest-ac9ee.firebaseapp.com',
    storageBucket: 'fcmtest-ac9ee.appspot.com',
    measurementId: 'G-JBY22QC82X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdJa04pib7_G54ElUoy1yYA6aObfc44_c',
    appId: '1:622273845776:android:86f6fbc27e7e830c404895',
    messagingSenderId: '622273845776',
    projectId: 'fcmtest-ac9ee',
    storageBucket: 'fcmtest-ac9ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA4tpAO2EgQUtCituA-87-Gmxt_PgqX40',
    appId: '1:622273845776:ios:8f18310c9f830448404895',
    messagingSenderId: '622273845776',
    projectId: 'fcmtest-ac9ee',
    storageBucket: 'fcmtest-ac9ee.appspot.com',
    iosClientId: '622273845776-1g6jdknt70ubfdj0kce4cqu3ffvgf9fn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA4tpAO2EgQUtCituA-87-Gmxt_PgqX40',
    appId: '1:622273845776:ios:8f18310c9f830448404895',
    messagingSenderId: '622273845776',
    projectId: 'fcmtest-ac9ee',
    storageBucket: 'fcmtest-ac9ee.appspot.com',
    iosClientId: '622273845776-1g6jdknt70ubfdj0kce4cqu3ffvgf9fn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcm',
  );
}
